# Generated by Django 3.1.1 on 2020-10-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTypeSale', models.CharField(max_length=100)),
                ('numSale', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.FileField(blank=True, upload_to='img/products_image')),
                ('TypeSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.typesale')),
                ('Types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.types')),
            ],
        ),
    ]
