# Generated by Django 3.1.1 on 2020-10-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typesale',
            name='numSale',
        ),
        migrations.AddField(
            model_name='products',
            name='numSale',
            field=models.IntegerField(default=0),
        ),
    ]
